import pandas as pd
import uuid
import random
import os
import pickle

CITIES = ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", "Pune", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Tenkasi"]
ROLES = ["SDE Intern", "Data Science Intern", "Frontend Dev", "Backend Dev", "PM Intern", "UI/UX Intern", "Marketing Intern"]
SECTORS = ["IT", "Finance", "Core", "E-commerce", "HealthTech"]
SKILLS_POOL = ["Python", "React", "Node.js", "SQL", "AWS", "Machine Learning", "Figma", "UI/UX", "Java", "C++", "Docker", "Kubernetes", "Tailwind", "Project Management", "Communication", "Excel", "Market Research", "AutoCAD", "PLC", "Mechanical Design"]
CASTES = ["General", "OBC", "SC", "ST", "EWS"]
MAJORS = ["Computer Science", "AI & Data Science", "Mechanical", "ECE", "Business Management"]

REAL_NAMES = [
    "Arjun Sharma", "Priya Patel", "Rahul Verma", "Ananya Iyer", "Siddharth Malhotra", 
    "Ishita Gupta", "Vikram Singh", "Sneha Reddy", "Aditya Rao", "Kavya Nair",
    "Rohan Deshmukh", "Anjali Bose", "Manish Joshi", "Tanvi Kulkarni", "Abhishek Das"
]

COMPANY_NAMES = [
    "RELIANCE INDUSTRIES LIMITED", "TATA CONSULTANCY SERVICES LIMITED", "HDFC BANK LIMITED",
    "OIL AND NATURAL GAS CORPORATION LIMITED", "INFOSYS LIMITED", "NTPC LIMITED",
    "TATA STEEL LIMITED", "ITC LIMITED", "INDIAN OIL CORPORATION LIMITED", "ICICI BANK LIMITED",
    "POWER GRID CORPORATION OF INDIA LIMITED", "TATA SONS PRIVATE LIMITED", "WIPRO LIMITED",
    "HCL TECHNOLOGIES LIMITED", "HINDUSTAN ZINC LIMITED", "RELIANCE JIO INFOCOMM LIMITED",
    "MAHANADI COALFIELDS LIMITED", "NMDC LIMITED", "HINDUSTAN UNILEVER LIMITED", "REC LIMITED",
    "JSW STEEL LIMITED", "GAIL (INDIA) LIMITED", "COGNIZANT TECHNOLOGY SOLUTIONS INDIA PRIVATE LIMITED",
    "LARSEN AND TOUBRO LIMITED", "AXIS BANK LIMITED", "NORTHERN COALFIELDS LIMITED", "OIL INDIA LIMITED",
    "HINDUSTAN PETROLEUM CORPORATION LIMITED", "JINDAL STEEL & POWER LIMITED", "RELIANCE RETAIL LIMITED",
    "NUCLEAR POWER CORPORATION OF INDIA LIMITED", "TECH MAHINDRA LIMITED", "POWER FINANCE CORPORATION LIMITED",
    "ULTRATECH CEMENT LIMITED", "INDUSIND BANK LTD.", "NHPC LIMITED", "STEEL AUTHORITY OF INDIA LIMITED",
    "MARUTI SUZUKI INDIA LIMITED", "VEDANTA LIMITED", "BHARAT PETROLEUM CORPORATION LIMITED",
    "SERUM INSTITUTE OF INDIA PRIVATE LIMITED", "BAJAJ FINANCE LIMITED", "MAHINDRA AND MAHINDRA LIMITED",
    "HINDUSTAN AERONAUTICS LIMITED", "SAMSUNG INDIA ELECTRONICS PRIVATE LIMITED", "BAJAJ AUTO LIMITED.",
    "KOTAK MAHINDRA BANK LIMITED", "ACCENTURE SOLUTIONS PRIVATE LIMITED", "SHRIRAM FINANCE LIMITED",
    "MUTHOOT FINANCE LIMITED", "RUNGTA SONS PVT LTD", "HERO MOTOCORP LIMITED", "COAL INDIA LTD GOVT OF INDIA UNDERTAKING",
    "MEGHA ENGINEERING & INFRASTRUCTURES LIMITED", "AMBUJA CEMENTS LIMITED", "INDUS TOWERS LIMITED",
    "CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED", "SOUTH EASTERN COALFIELDS LIMITED", "ASIAN PAINTS LIMITED",
    "IBM INDIA PRIVATE LIMITED", "GRASIM INDUSTRIES LTD", "SAMMAAN CAPITAL LIMITED", "BANDHAN BANK LIMITED",
    "BIOP STEELS & POWER PRIVATE LIMITED", "SHREE CEMENT LIMITED", "SERUM INSTITUTE LIFE SCIENCES PRIVATE LIMITED",
    "ARCELORMITTAL NIPPON STEEL INDIA LIMITED", "CIPLA LIMITED", "UPL LIMITED", "SJVN LIMITED", "NUMALIGARH REFINERY LTD",
    "ADANI PORTS AND SPECIAL ECONOMIC ZONE LIMITED", "ORACLE FINANCIAL SERVICES SOFTWARE LIMITED", "NLC INDIA LIMITED",
    "NATIONAL STOCK EXCHANGE OF INDIA LTD.", "THE ASSOCIATED BUILDING COMPANY LIMITED", "DIVI S LABORATORIES LIMITED",
    "INDIAN RAILWAY FINANCE CORPORATION LIMITED", "LTIMINDTREE LIMITED", "ZOHO CORPORATION PRIVATE LIMITED",
    "ACC LIMITED", "SUN TV NETWORK LIMITED", "CENTRAL COALFIELDS LIMITED", "TITAN COMPANY LIMITED",
    "SIKKA PORTS & TERMINALS LIMITED", "DR.REDDY S LABORATORIES LTD", "M.P. AGROTONICS LIMITED", "BRITANNIA INDUSTRIES LTD",
    "HINDALCO INDUSTRIES LIMITED", "JAMNAGAR UTILITIES & POWER PRIVATE LIMITED", "RECKITT BENCKISER (INDIA) PRIVATE LIMITED",
    "BHARAT ALUMINIUM CO LTD", "HYUNDAI MOTOR INDIA LIMITED", "CHOLAMANDALAM INVESTMENT AND FINANCE COMPANY LIMITED",
    "NATIONAL ALUMINIUM CO LTD", "BENGAL FINANCE AND INVESTMENT PRIVATE LIMITED", "BHARAT ELECTRONICS LIMITED",
    "SUN PHARMA LABORATORIES LIMITED", "THE SINGARENI COLLIERIES COMPANY LIMITED", "SBI CARDS AND PAYMENT SERVICES LIMITED",
    "ZYDUS LIFESCIENCES LIMITED", "THE FEDERAL BANK LTD", "PIRAMAL CAPITAL & HOUSING FINANCE LIMITED",
    "WINSOL SOLAR FIELDS (POLEPALLY) PRIVATE LIMITED", "ZEE ENTERTAINMENT ENTERPRISES LIMITED", "GLENMARK PHARMACEUTICALS LIMITED",
    "MAHINDRA AND MAHINDRA FINANCIAL SERVICES LIMITED", "ODISHA MINING CORPORATION LIMITED", "ICICI LOMBARD GENERAL INSURANCE COMPANY LIMITED",
    "LUPIN LIMITED", "AVENUE SUPERMARTS LIMITED", "PERNOD RICARD INDIA PRIVATE LIMITED", "EICHER MOTORS LIMITED",
    "DABUR INDIA LIMITED", "ZERODHA BROKING LIMITED", "GODREJ CONSUMER PRODUCTS LIMITED", "MANAPPURAM FINANCE LIMITED",
    "SIEMENS LIMITED", "HDFC ASSET MANAGEMENT COMPANY LIMITED", "PIDILITE INDUSTRIES LIMITED", "MPHASIS LIMITED",
    "ICICI PRUDENTIAL ASSET MANAGEMENT COMPANY LIMITED", "TANJORE POWER LIMITED", "CONTAINER CORPORATION OF INDIA LIMITED",
    "CHAMBAL FERTILISERS AND CHEMICALS LIMITED", "ADANI HARBOUR SERVICES LIMITED", "MANKIND PHARMA LIMITED",
    "YARROW INFRASTRUCTURE PRIVATE LIMITED", "RUNGTA MINES LIMITED", "SBI LIFE INSURANCE COMPANY LIMITED",
    "COROMANDEL INTERNATIONAL LIMITED", "HONDA MOTORCYCLE AND SCOOTER INDIA PVT LTD", "APPLE INDIA PRIVATE LIMITED",
    "SUN PHARMACEUTICAL INDUSTRIES LIMITED", "BAJAJ ALLIANZ GENERAL INSURANCE COMPANY LIMITED", "BOSCH LIMITED",
    "JOHNSON & JOHNSON PRIVATE LIMITED", "JINDAL ALUMINIUM LIMITED.", "BALKRISHNA INDUSTRIES LIMITED", "THDC INDIA LIMITED",
    "GOOGLE IT SERVICES INDIA PRIVATE LIMITED", "USV PRIVATE LIMITED", "MACLEODS PHARMACEUTICALS LTD", "HDB FINANCIAL SERVICES LIMITED",
    "MRF LIMITED", "TATA MOTORS LIMITED", "COLGATE-PALMOLIVE (INDIA) LIMITED", "ICICI SECURITIES LIMITED",
    "JCB INDIA LIMITED", "DILIP BUILDCON LIMITED", "MARICO LIMITED", "INTERNATIONAL TRACTORS LIMITED",
    "POLYCAB INDIA LIMITED", "DELOITTE CONSULTING INDIA PRIVATE LIMITED", "HSBC SOFTWARE DEVELOPMENT (INDIA) PRIVATE LIMITED",
    "TORRENT POWER LIMITED", "AUROBINDO PHARMA LTD", "RAIL VIKAS NIGAM LIMITED", "L G ELECTRONICS INDIA PRIVATE LIMITED",
    "INTEL TECHNOLOGY INDIA PRIVATE LIMITED", "SUNDARAM FINANCE LIMITED", "ASHOK LEYLAND LIMITED", "ALEMBIC PHARMACEUTICALS LIMITED",
    "HAVELLS INDIA LIMITED", "EXIDE INDUSTRIES LIMITED", "NIRMA LIMITED", "INTAS PHARMACEUTICALS LIMITED",
    "ATC TELECOM INFRASTRUCTURE PRIVATE LIMITED", "ADITYA BIRLA FINANCE LIMITED", "JOHN DEERE INDIA PRIVATE LIMITED",
    "NHDC LIMITED", "BHARTI TELEMEDIA LIMITED", "SRF LIMITED", "YARDI SOFTWARE INDIA PRIVATE LIMITED",
    "CULVER MAX ENTERTAINMENT PRIVATE LIMITED", "DHARAMPAL SATYAPAL LIMITED", "BHILOSA INDUSTRIES PRIVATE LIMITED",
    "J. K. CEMENT LIMITED.", "TVS MOTOR COMPANY LIMITED", "BA CONTINUUM INDIA PRIVATE LIMITED", "COCA COLA INDIA PRIVATE LIMITED",
    "ENGINEERS INDIA LIMITED", "GUJARAT NARMADA VALLEY FERTILIZERS & CHEMICALS LIMITED", "MOIL LIMITED",
    "HDFC LIFE INSURANCE COMPANY LIMITED", "THE RAMCO CEMENTS LIMITED", "GUJARAT GAS LIMITED",
    "PROCTER & GAMBLE HYGIENE AND HEALTH CARE LIMITED", "DCM SHRIRAM LIMITED", "L&T TECHNOLOGY SERVICES LIMITED",
    "ORACLE INDIA PRIVATE LIMITED", "BERGER PAINTS INDIA LIMITED", "IDFC FIRST BANK LIMITED", "HPCL-MITTAL ENERGY LIMITED",
    "PNB HOUSING FINANCE LIMITED", "TATA CHEMICALS LIMITED", "FINOLEX INDUSTRIES LIMITED", "GLAND PHARMA LTD",
    "GUJARAT STATE PETRONET LIMITED", "WELLS FARGO INTERNATIONAL SOLUTIONS PRIVATE LIMITED", "ERICSSON INDIA PRIVATE LIMITED",
    "HONEYWELL AUTOMATION INDIA LIMITED", "ORISSA METALIKS PRIVATE LIMITED", "AMARA RAJA ENERGY & MOBILITY LIMITED",
    "DELL INTERNATIONAL SERVICES INDIA PRIVATE LIMITED", "HSBC ELECTRONIC DATA PROCESSING INDIA PRIVATE LIMITED",
    "BHARAT DYNAMICS LIMITED", "MONDELEZ INDIA FOODS PRIVATE LIMITED", "ATLAS COPCO (INDIA) PRIVATE LIMITED",
    "MAHANAGAR GAS LIMITED", "COCHIN SHIPYARD LIMITED", "IPCA LABORATORIES LIMITED", "THE SUPREME INDUSTRIES LIMITED",
    "PARLE BISCUITS PRIVATE LIMITED", "CATERPILLAR INDIA PRIVATE LIMITED", "INDRAPRASTHA GAS LIMITED", "ADANI ENTERPRISES LIMITED",
    "BENNETT COLEMAN AND COMPANY LIMITED", "J. P. MORGAN SERVICES INDIA PRIVATE LIMITED", "KARNATAKA POWER TRANSMISSION CORPORATION LIMITED",
    "KIRAN GEMS PRIVATE LIMITED", "BHARAT FORGE LTD", "EIT SERVICES INDIA PRIVATE LIMITED",
    "MANGALORE REFINERY AND PETROCHEMICALS LIMITED", "BHARAT BIOTECH INTERNATIONAL LIMITED", "NAYARA ENERGY LIMITED",
    "VARSITY EDUCATION MANAGEMENT PRIVATE LIMITED", "APOLLO TYRES LIMITED.", "PETRONET LNG LIMITED", "AJANTA PHARMA LIMITED",
    "MAZAGON DOCK SHIPBUILDERS LIMITED", "NOKIA SOLUTIONS AND NETWORKS INDIA PRIVATE LIMITED", "NATIONAL PAYMENTS CORPORATION OF INDIA",
    "ARAVALI POWER COMPANY PRIVATE LIMITED", "ADANI HAZIRA PORT LIMITED", "HDFC SECURITIES LIMITED", "AARTI INDUSTRIES LTD",
    "PATAKA INDUSTRIES PRIVATE LIMITED", "KANSAI NEROLAC PAINTS LIMITED", "TATA CAPITAL FINANCIAL SERVICES LIMITED",
    "ADANI WILMAR LIMITED", "TATA CONSUMER PRODUCTS LIMITED", "GHARDA CHEMICALS LIMITED",
    "BOSCH GLOBAL SOFTWARE TECHNOLOGIES PRIVATE LIMITED", "IL&FS TAMIL NADU POWER COMPANY LIMITED",
    "GUJARAT STATE FERTILIZERS & CHEMICALS LIMITED", "CUMMINS INDIA LIMITED", "SOBHA LIMITED", "EDGEVERVE SYSTEMS LIMITED",
    "PERSISTENT SYSTEMS LIMITED", "TOYOTA KIRLOSKAR MOTOR PRIVATE LIMITED", "BARCLAYS GLOBAL SERVICE CENTRE PRIVATE LIMITED",
    "MAHASHIAN DI HATTI PRIVATE LIMITED", "CITICORP SERVICES INDIA PRIVATE LIMITED", "MICRO LABS LIMITED",
    "EQUITAS SMALL FINANCE BANK LIMITED", "RSPL LIMITED", "TAMILNAD MERCANTILE BANK LIMITED", "UTKAL ALUMINA INTERNATIONAL LIMITED.",
    "UNITED SPIRITS LIMITED", "DLF LIMITED", "BAGMANE DEVELOPERS PRIVATE LIMITED", "VOLTAS LIMITED",
    "GAWAR CONSTRUCTION LIMITED.", "ATUL LIMITED", "TORRENT PHARMACEUTICALS LTD", "AIA ENGINEERING LIMITED",
    "MODERN ROAD MAKERS P LTD", "BAYER CROPSCIENCE LIMITED", "HONEYWELL TECHNOLOGY SOLUTIONS LAB PRIVATE LIMITED",
    "MACROTECH DEVELOPERS LIMITED", "RITES LIMITED", "GODAWARI POWER AND ISPAT LIMITED",
    "CORTEVA AGRISCIENCE SEEDS PRIVATE LIMITED", "GLAXOSMITHKLINE PHARMACEUTICALS LIMITED", "CITY UNION BANK LIMITED",
    "SAINT-GOBAIN INDIA PRIVATE LIMITED", "TOPCON SOKKIA INDIA PRIVATE LIMITED", "LAURUS LABS LIMITED",
    "INGRAM MICRO INDIA PRIVATE LIMITED", "THE CLEARING CORPORATION OF INDIA LIMITED", "SBI GENERAL INSURANCE COMPANY LIMITED",
    "TATA COMMUNICATIONS LIMITED", "TATA POWER DELHI DISTRIBUTION LIMITED", "GODREJ SEEDS & GENETICS LIMITED",
    "CROMPTON GREAVES CONSUMER ELECTRICALS LIMITED", "KOTAK MAHINDRA PRIME LIMITED", "BRAHMAPUTRA CRACKER AND POLYMER LIMITED",
    "PROCTER & GAMBLE HOME PRODUCTS PRIVATE LIMITED", "PATANJALI AYURVED LIMITED", "MSPL LIMITED", "LIC HOUSING FINANCE LTD",
    "JSW STEEL COATED PRODUCTS LIMITED", "INFOSYS BPM LIMITED", "AU SMALL FINANCE BANK LIMITED", "BALRAMPUR CHINI MILLS LTD",
    "RBL BANK LIMITED", "B. G. SHIRKE CONSTRUCTION TECHNOLOGY PRIVATE LIMITED", "URANIUM CORPORATION OF INDIA LIMITED",
    "JINDAL SAW LIMITED", "ADANI GANGAVARAM PORT LIMITED", "JK PAPER LIMITED", "HDFC ERGO GENERAL INSURANCE COMPANY LIMITED",
    "WHIRLPOOL OF INDIA LIMITED", "RELIANCE RETAIL VENTURES LIMITED", "EASTERN COALFIELDS LTD", "PI INDUSTRIES LIMITED",
    "KEC INTERNATIONAL LIMITED", "K.P.R. MILL LIMITED", "INDIAN RAILWAY CATERING AND TOURISM CORPORATION LIMITED",
    "SBI FUNDS MANAGEMENT LIMITED", "THE NEW INDIA ASSURANCE COMPANY LIMITED", "AMERICAN EXPRESS(INDIA) PRIVATE LIMITED",
    "PNC INFRATECH LIMITED", "JAQUAR AND COMPANY PRIVATE LIMITED", "ADOBE SYSTEMS INDIA PRIVATE LIMITED",
    "MALABAR GOLD LIMITED", "TRIDENT LIMITED", "BAJAJ ALLIANZ LIFE INSURANCE COMPANY LIMITED", "WNS GLOBAL SERVICES PRIVATE LIMITED",
    "ADANI TOTAL GAS LIMITED", "SHELL ENERGY INDIA PRIVATE LIMITED", "STERLITE TECHNOLOGIES LIMITED", "IRCON INTERNATIONAL LIMITED",
    "KOTAK SECURITIES LIMITED", "WELSPUN LIVING LIMITED", "JSW ENERGY (BARMER) LIMITED", "TAFE MOTORS AND TRACTORS LIMITED",
    "WESTERN COALFIELDS LIMITED", "GHCL LIMITED", "MAX LIFE INSURANCE COMPANY LIMITED", "VMWARE SOFTWARE INDIA PRIVATE LIMITED",
    "GMR HYDERABAD INTERNATIONAL AIRPORT LIMITED", "STANDARD CHARTERED GLOBAL BUSINESS SERVICES PRIVATE LIMITED",
    "PRESTIGE ESTATES PROJECTS LIMITED", "ABBOTT INDIA LIMITED", "MICROSOFT INDIA (R&D) PRIVATE LIMITED",
    "PANASONIC LIFE SOLUTIONS INDIA PRIVATE LIMITED", "SHYAM SEL AND POWER LIMITED", "THRIVENI EARTHMOVERS PRIVATE LIMITED",
    "THE KARNATAKA BANK LIMITED", "PIRAMAL ENTERPRISES LIMITED", "DEEPAK NITRITE LIMITED", "SUNDRAM FASTENERS LIMITED",
    "TRANSUNION CIBIL LIMITED", "SMFG INDIA CREDIT COMPANY LIMITED", "PATANJALI FOODS LIMITED", "DEUTSCHE INDIA PRIVATE LIMITED",
    "VODAFONE IDEA LIMITED", "GILLETTE INDIA LIMITED", "APOLLO HOSPITALS ENTERPRISE LIMITED", "HALDIRAM SNACKS PRIVATE LIMITED",
    "THE GREAT EASTERN SHIPPING COMPANY LIMITED", "BHANSALI ENGINEERING POLYMERS LIMITED", "EBIXCASH LIMITED",
    "EDELWEISS ASSET RECONSTRUCTION COMPANY LIMITED", "ADITYA BIRLA SUN LIFE AMC LIMITED", "TATA CAPITAL HOUSING FINANCE LIMITED",
    "GRT JEWELLERS (INDIA) PRIVATE LIMITED", "ENDURANCE TECHNOLOGIES LIMITED", "CAN FIN HOMES LIMITED", "UNITED BREWERIES LIMITED",
    "SUPER CASSETTES INDUSTRIES PRIVATE LIMITED", "STAR INDIA PRIVATE LIMITED", "SHREE RAMKRISHNA EXPORTS PRIVATE LIMITED",
    "ESSEL MINING & INDUSTRIES LTD.", "DCB BANK LIMITED", "NOVATEUR ELECTRICAL & DIGITAL SYSTEMS PRIVATE LIMITED", "ECGC LIMITED",
    "KITEX CHILDRENSWEAR LIMITED", "CUMMINS TECHNOLOGIES INDIA PRIVATE LIMITED", "DALMIA CEMENT (BHARAT) LIMITED",
    "KARNAVATI AVIATION PRIVATE LIMITED", "CITIGROUP GLOBAL MARKETS INDIA PRIVATE LIMITED", "COLOURTEX INDUSTRIES PRIVATE LIMITED",
    "CYIENT LIMITED", "NSE CLEARING LIMITED", "BHUSHAN POWER & STEEL LIMITED", "ADANI TRANSMISSION (INDIA) LIMITED",
    "BAJAJ HOLDINGS & INVESTMENT LIMITED.", "GUJARAT ALKALIES AND CHEMICALS LIMITED", "BRAKES INDIA PRIVATE LIMITED",
    "APCO INFRATECH PRIVATE LIMITED", "ICICI SECURITIES PRIMARY DEALERSHIP LIMITED", "ALKEM LABORATORIES LIMITED",
    "FINOLEX CABLES LIMITED", "INDIAN METALS AND FERRO ALLOYS LTD.", "WIPRO ENTERPRISES PRIVATE LIMITED", "KIOCL LIMITED",
    "KARNATAKA RURAL INFRASTRUCTURE DEVELOPMENT LIMITED", "ATRIA CONVERGENCE TECHNOLOGIES LIMITED", "GRANULES INDIA LIMITED",
    "ASHOKA BUILDCON LIMITED", "GUJARAT MINERAL DEVELOPMENT CORPORATION LIMITED", "JUBILANT FOODWORKS LIMITED",
    "GENPACT INDIA PRIVATE LIMITED", "KOTAK MAHINDRA LIFE INSURANCE COMPANY LIMITED", "BAJAJ HOUSING FINANCE LIMITED", "EMAMI LIMITED",
    "INDIAN ENERGY EXCHANGE LIMITED", "BIRLA CARBON INDIA PRIVATE LIMITED", "PFIZER LIMITED", "NIPPON LIFE INDIA ASSET MANAGEMENT LIMITED",
    "HINDUSTAN COCA-COLA BEVERAGES PRIVATE LIMITED", "WONDER CEMENT LIMITED", "DXC TECHNOLOGY INDIA PRIVATE LIMITED",
    "MOTILAL OSWAL FINANCIAL SERVICES LIMITED", "CGI INFORMATION SYSTEMS AND MANAGEMENT CONSULTANTS PRIVATE LIMITED",
    "MUSIGMA BUSINESS SOLUTIONS PRIVATE LIMITED", "ADANI POWER LIMITED", "EMCURE PHARMACEUTICALS LIMITED",
    "DECCAN FINE CHEMICALS (INDIA) PRIVATE LIMITED", "G R INFRAPROJECTS LIMITED", "TATA AIG GENERAL INSURANCE COMPANY LIMITED",
    "D P F TEXTILES PRIVATE LIMITED", "FIDELITY BUSINESS SERVICES INDIA PRIVATE LIMITED", "RASHTRIYA CHEMICALS AND FERTILIZERS LIMITED",
    "INFO EDGE (INDIA) LIMITED", "EVEREST FOOD PRODUCTS PRIVATE LIMITED",
    "TAMILNADU POWER FINANCE AND INFRASTRUCTURE DEVELOPMENT CORPORATION LIMITED", "KAJARIA CERAMICS LIMITED",
    "MAITHAN ALLOYS LTD.", "HUAWEI TELECOMMUNICATIONS (INDIA) COMPANY PRIVATE LIMITED", "IIFL HOME FINANCE LIMITED",
    "GUJARAT FLUOROCHEMICALS LIMITED", "VENCO RESEARCH AND BREEDING FARM PRIVATE LIMITED", "RASHMI CEMENT LIMITED",
    "SKODA AUTO VOLKSWAGEN INDIA PRIVATE LIMITED", "NTPC TAMIL NADU ENERGY COMPANY LIMITED", "NTPC-SAIL POWER COMPANY LIMITED",
    "FRIGERIO CONSERVA ALLANA PRIVATE LIMITED", "TUBE INVESTMENTS OF INDIA LIMITED",
    "MAHARASHTRA EASTERN GRID POWER TRANSMISSION COMPANY LIMITED", "CYBAGE SOFTWARE PRIVATE LIMITED",
    "SHRIRAM GENERAL INSURANCE COMPANY LIMITED", "APARNA INFRAHOUSING PRIVATE LIMITED (PART IX )", "ESCORTS KUBOTA LIMITED",
    "SAMSUNG R&D INSTITUTE INDIA - BANGALORE PRIVATE LIMITED", "HEIDELBERGCEMENT INDIA LIMITED.", "JSW ENERGY LIMITED",
    "SKF INDIA LIMITED", "SCHNEIDER ELECTRIC INDIA PRIVATE LIMITED", "INOX AIR PRODUCTS PRIVATE LIMITED",
    "INDIAN RENEWABLE ENERGY DEVELOPMENT AGENCY LIMITED", "NCC LIMITED", "RELIANCE CORPORATE IT PARK LIMITED", "REDINGTON LIMITED",
    "TRANSMISSION CORPORATION OF TELANGANA LIMITED", "VIACOM 18 MEDIA PRIVATE LIMITED", "FRIGORIFICO ALLANA PRIVATE LIMITED",
    "FRANKLIN TEMPLETON ASSET MANAGEMENT (INDIA) PRIVATE LIMITED", "HP INDIA SALES PRIVATE LIMITED",
    "HERBALIFE INTERNATIONAL INDIA PRIVATE LIMITED", "ICICI PRUDENTIAL LIFE INSURANCE COMPANY LIMITED",
    "YASHODA HEALTHCARE SERVICES PRIVATE LIMITED", "AGROCEL INDUSTRIES PRIVATE LIMITED", "3M INDIA LIMITED",
    "KNR CONSTRUCTIONS LIMITED", "GLENMARK LIFE SCIENCES LIMITED", "SUVEN PHARMACEUTICALS LIMITED",
    "SOCIETE GENERALE SECURITIES INDIA PRIVATE LIMITED", "PRAKASH INDUSTRIES LIMITED", "IREL (INDIA) LIMITED", "D B POWER LIMITED",
    "SHARDA CROPCHEM LIMITED", "PIRAMAL PHARMA LIMITED", "TRIVENI ENGINEERING AND INDUSTRIES LIMITED",
    "NIYOGI ENTERPRISE PRIVATE LIMITED", "MICROSOFT CORPORATION (INDIA) PVT LTD", "FIAT INDIA AUTOMOBILES PRIVATE LIMITED",
    "MERCEDES-BENZ RESEARCH AND DEVELOPMENT INDIA PRIVATE LIMITED", "CREDIT SUISSE SECURITIES (INDIA) PRIVATE LIMITED",
    "ASIAN FAB TEC LIMITED", "SIGNIFY INNOVATIONS INDIA LIMITED", "SARDA ENERGY & MINERALS LIMITED", "PAGE INDUSTRIES LIMITED",
    "SAVEX TECHNOLOGIES PRIVATE LIMITED", "SCHNEIDER ELECTRIC IT BUSINESS INDIA PRIVATE LIMITED", "THE DHAMRA PORT COMPANY LIMITED",
    "ROMA BUILDERS PRIVATE LIMITED", "DR. LAL PATHLABS LIMITED", "SUMITOMO CHEMICAL INDIA LIMITED",
    "CREDIT SUISSE SERVICES (INDIA) PRIVATE LIMITED", "ASTRAL LIMITED", "AVANTI FEEDS LIMITED", "KAMARAJAR PORT LIMITED",
    "KHAZANA JEWELLERY PRIVATE LIMITED", "STAR CEMENT LIMITED", "ADANI SOLAR ENERGY AP SIX PRIVATE LIMITED",
    "HARI KRISHNA EXPORTS PRIVATE LIMITED", "POLYPLEX CORPORATION LIMITED", "RASHMI METALIKS LIMITED", "GUJARAT PIPAVAV PORT LIMITED",
    "WEST BENGALSTATE ELECTRICITY TRANSMISSION COMPANY LIMITED", "HATSUN AGRO PRODUCT LIMITED", "FIVE-STAR BUSINESS FINANCE LIMITED",
    "ITC INFOTECH INDIA LIMITED", "IIFL FINANCE LIMITED", "HALDIRAM FOODS INTERNATIONAL PRIVATE LIMITED", "DBS BANK INDIA LIMITED",
    "BRIGADE ENTERPRISES LIMITED", "BATA INDIA LTD", "OBEROI REALTY LIMITED", "FORTIS HEALTHCARE LIMITED", "INTERGLOBE AVIATION LIMITED",
    "JOYALUKKAS INDIA LIMITED", "KALYAN JEWELLERS INDIA LIMITED", "CESC LTD", "METRO BRANDS LIMITED", "MAYUR UNIQUOTERS LIMITED",
    "OMEGA HEALTHCARE MANAGEMENT SERVICES PRIVATE LIMITED", "PC JEWELLER LIMITED", "ASTRAZENECA PHARMA INDIA LIMITED",
    "STERLITE POWER TRANSMISSION LIMITED", "ASTER DM HEALTHCARE LIMITED", "NARAYANA HRUDAYALAYA LIMITED",
    "ICICI HOME FINANCE COMPANY LIMITED", "MIRZA INTERNATIONAL LIMITED", "RIYA TRAVEL AND TOURS (INDIA) PRIVATE LIMITED",
    "PUMA SPORTS INDIA PRIVATE LIMITED", "NIKE INDIA PRIVATE LIMITED", "RADISSON HOTELS (SOUTH ASIA) PRIVATE LIMITED",
    "MAX HEALTHCARE INSTITUTE LIMITED", "EIH ASSOCIATED HOTELS LIMITED", "EXPEDIA ONLINE TRAVEL SERVICES INDIA PRIVATE LIMITED",
    "TRIBHOVANDAS BHIMJI ZAVERI LIMITED", "MANIPAL HOSPITALS PRIVATE LIMITED", "BHARTIYA INTERNATIONAL LIMITED", "GLOBAL HEALTH LIMITED",
    "LEMON TREE HOTELS LIMITED", "THOMAS COOK (INDIA) LIMITED", "FARIDA SHOES PRIVATE LIMITED", "JSW SPORTS PRIVATE LIMITED",
    "SANSPAREILS GREENLANDS PRIVATE LIMITED", "MAHINDRA LIFESPACE DEVELOPERS LIMITED", "SOCCER INTERNATIONAL PRIVATE LIMITED",
    "AMRAPALI JEWELS PRIVATE LIMITED", "KOLTE-PATIL DEVELOPERS LIMITED", "CARATLANE TRADING PRIVATE LIMITED",
    "BOOKING.COM INDIA SUPPORT & MARKETING SERVICES PRIVATE LIMITED", "DECATHLON SPORTS INDIA PRIVATE LIMITED",
    "TATA SIA AIRLINES LIMITED", "COSCO (INDIA) LIMITED", "HIDESIGN INDIA PRIVATE LIMITED", "SHIV-NARESH SPORTS PRIVATE LIMITED",
    "MARRIOTT HOTELS INDIA PRIVATE LIMITED (TRF.)", "YATRA FOR BUSINESS PRIVATE LIMITED", "ADIDAS INDIA MARKETING PRIVATE LIMITED",
    "DLF CYBER CITY DEVELOPERS LIMITED"
]

def generate_data():
    # 10 Users
    users = []
    names_sample = random.sample(REAL_NAMES, 10)
    for i in range(10):
        skills = random.sample(SKILLS_POOL, random.randint(3, 6))
        users.append({
            "user_id": str(uuid.uuid4()),
            "name": names_sample[i],
            "email": f"{names_sample[i].lower().replace(' ', '.')}@example.com",
            "caste": random.choice(CASTES),
            "location": random.choice(CITIES),
            "family_income": random.choice(["< 2L", "2L - 5L", "5L - 8L", "> 8L"]),
            "major": random.choice(MAJORS),
            "skills": ", ".join(skills)
        })
    
    # 50 Jobs
    jobs = []
    # Mix top companies in
    top_picks = random.sample(COMPANY_NAMES[:20], 10)
    rest_picks = random.sample(COMPANY_NAMES[20:], 40)
    all_picks = top_picks + rest_picks
    random.shuffle(all_picks)

    for i in range(50):
        req_skills = random.sample(SKILLS_POOL, random.randint(3, 5))
        jobs.append({
            "job_id": str(uuid.uuid4()),
            "company": all_picks[i],
            "role": random.choice(ROLES),
            "sector": random.choice(SECTORS),
            "required_skills": ", ".join(req_skills),
            "location": random.choice(CITIES),
            "stipend": random.randint(10000, 45000)
        })

    pd.DataFrame(users).to_csv('backend/users.csv', index=False)
    pd.DataFrame(jobs).to_csv('backend/jobs.csv', index=False)
    
    # Ensure empty applications and selections files exist
    pd.DataFrame(columns=["user_id", "job_id", "timestamp"]).to_csv('backend/applications.csv', index=False)
    pd.DataFrame(columns=["user_id", "job_id", "timestamp"]).to_csv('backend/selections.csv', index=False)
    
    print("Successfully generated 10 users and 50 jobs. Application and Selection files cleared.")

if __name__ == "__main__":
    generate_data()
